---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    config:
      .eslintrc
ratings:
  paths:
  - "**.js"
exclude_paths:
- node_modules/
- tests/
- coverage/
